[package]
name = "andiskaz"
version = "0.1.0"
authors = ["brunoczim <brunoczim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "^1.6.0"
lazy_static = "^1.4"
crossterm = "^0.18"

[dependencies.tokio]
version = "^0.2.11"
features = [
    "macros",
    "io-util",
    "io-std",
    "blocking",
    "sync",
    "rt-threaded",
    "fs",
    "time"
]
