(function() {var implementors = {};
implementors["andiskaz"] = [{"text":"impl Ord for TermString","synthetic":false,"types":[]},{"text":"impl Ord for TermGrapheme","synthetic":false,"types":[]},{"text":"impl&lt;'buf&gt; Ord for StringOrGraphm&lt;'buf&gt;","synthetic":false,"types":[]},{"text":"impl Ord for Coord2","synthetic":false,"types":[]},{"text":"impl Ord for Brightness","synthetic":false,"types":[]},{"text":"impl Ord for BasicColor","synthetic":false,"types":[]},{"text":"impl Ord for CmyColor","synthetic":false,"types":[]},{"text":"impl Ord for GrayColor","synthetic":false,"types":[]},{"text":"impl Ord for Color8Kind","synthetic":false,"types":[]},{"text":"impl Ord for Color8","synthetic":false,"types":[]},{"text":"impl Ord for RgbColor","synthetic":false,"types":[]},{"text":"impl Ord for Color2","synthetic":false,"types":[]},{"text":"impl Ord for Color","synthetic":false,"types":[]},{"text":"impl Ord for Tile","synthetic":false,"types":[]}];
implementors["arc_swap"] = [{"text":"impl&lt;T:&nbsp;Ord&gt; Ord for ConstantDeref&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Ord&gt; Ord for Constant&lt;T&gt;","synthetic":false,"types":[]}];
implementors["bytes"] = [{"text":"impl Ord for Bytes","synthetic":false,"types":[]},{"text":"impl Ord for BytesMut","synthetic":false,"types":[]}];
implementors["crossterm"] = [{"text":"impl Ord for KeyModifiers","synthetic":false,"types":[]},{"text":"impl Ord for Attribute","synthetic":false,"types":[]},{"text":"impl Ord for Color","synthetic":false,"types":[]},{"text":"impl Ord for Colored","synthetic":false,"types":[]},{"text":"impl Ord for ClearType","synthetic":false,"types":[]}];
implementors["log"] = [{"text":"impl Ord for Level","synthetic":false,"types":[]},{"text":"impl Ord for LevelFilter","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Ord for Metadata&lt;'a&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Ord for MetadataBuilder&lt;'a&gt;","synthetic":false,"types":[]}];
implementors["mio"] = [{"text":"impl Ord for Interest","synthetic":false,"types":[]},{"text":"impl Ord for Token","synthetic":false,"types":[]}];
implementors["proc_macro2"] = [{"text":"impl Ord for Ident","synthetic":false,"types":[]}];
implementors["signal_hook_registry"] = [{"text":"impl Ord for SigId","synthetic":false,"types":[]}];
implementors["smallvec"] = [{"text":"impl&lt;A:&nbsp;Array&gt; Ord for SmallVec&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A::Item: Ord,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["syn"] = [{"text":"impl Ord for Lifetime","synthetic":false,"types":[]}];
implementors["tokio"] = [{"text":"impl Ord for Instant","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()