[package]
name = "andiskaz-core"
version = "0.1.0"
edition = "2021"

[dependencies.andiskaz-domain]
path = "../domain"

[dependencies.unicode-segmentation]
version = "^1.10"

[dependencies.async-trait]
version = "^0.1.73"
