[package]
name = "andiskaz-domain"
version = "0.1.0"
edition = "2021"

[dependencies.async-trait]
version = "^0.1"

[dependencies.gardiz]
git = "https://github.com/brunoczim/gardiz"
branch = "main"
optional = true

[features]
plane = ["gardiz"]
